apiVersion: apps/v1
kind: Deployment
metadata:
  name: feishubot
  labels:
    app: feishubot
spec:
  selector:
    matchLabels:
      app: feishubot
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: feishubot
    spec:
      containers:
      - name: feishubot
        image: {{ .Values.feishubot.image }}
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 500m
            memory: 500Mi
        env:
        - name: CHATAPI_SVC
          value: chatgpt-api
        ports:
        - containerPort: 9999
          name: http
---
apiVersion: v1
kind: Service
metadata:
  name: feishubot
spec:
  selector:
    app: feishubot
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 9999
    targetPort: 9999